### ISSUE TITLE
Header Styling Issues on Edge

### ISSUE THREAD

**Issue by R4356th** [snapwiki/snapwiki.github.io#10]
There are some styling issues in the header on Edge Version 86.0.622.63 (Official build) (64-bit). It looks like when the image alt text is being displayed instead of the image itself, the text "Snap<i>!</i> Wiki" is being displayed over it. Here is a screenshot-
<img width="259" alt="Wiki Website Header" src="https://user-images.githubusercontent.com/61620631/98263312-df89fe80-1fb0-11eb-81cc-68297628b642.png">

**Comment by GrahamSH-LLK** [comment]
Hmm... I think this could be solved by moving the image into this repo.

**Comment by R4356th** [comment]
I do not think that is the issue. It is being properly displayed now (there probably was some network connection issue when I took this screenshot).

**Comment by GrahamSH-LLK** [comment]
My guess is that it is the caching, which must be prioritizing on-repo images.

**Comment by R4356th** [comment]
Worth a try then...

**Comment by GrahamSH-LLK** [comment]
@R4356th Can you clear the cache, uninstall and try again?

**Comment by R4356th** [comment]
Yeah, this seems to be fixed.
