### ISSUE TITLE
Icon goes smaller in dark mode (Very minor issue)

### ISSUE THREAD

**Issue by Daniel4-Scratch** [snapwiki/snapwiki.github.io#12]
I noticed when I turn on dark mode on the website that the icon goes smaller
e.g.

![Screen Shot 2020-11-21 at 12 00 45 pm](https://user-images.githubusercontent.com/65277548/99863208-3a4a6980-2bf1-11eb-9cc8-044754e34a44.png)
![Screen Shot 2020-11-21 at 12 00 51 pm](https://user-images.githubusercontent.com/65277548/99863203-3585b580-2bf1-11eb-8284-c226e449b931.png)

<sup> also @GrahamSH-LLK or @R4356th I would suggest watching the repo for issue report updates

**Comment by GrahamSH-LLK** [comment]
Sorry, that was my fault. I thought I removed that. I'll fix it.
