### ISSUE TITLE
Stop Loading External Assets

### ISSUE THREAD

**Issue by R4356th** [snapwiki/snapwiki.github.io#18]
We should just make sure they are cached using the service worker for performance. This issue is not specific to this repository but also all other repositories.

* [x] snapwiki.github.io 
   * [x] Inter loaded from https://rsms.me
* [ ] wiki-mirror
   * [ ] Tailwind's CSS code loaded from Unpkg
 * [x] search
   * [x] Logo from Miraheze's static resource server

**Comment by GrahamSH-LLK** [comment]
What? We're loading jquery?!

**Comment by R4356th** [comment]
CLosing this as the repository is being archived. The wiki mirror issue can be tracked there.
