### ISSUE TITLE
How will the backup work?

### ISSUE THREAD

**Issue by GrahamSH-LLK** [snapwiki/snapwiki.github.io#2]
How will this backup work? Couldn't we just use web.archive.org? The normal wiki should never be completely down, it might just be read only. I think this is better suited as storage for data dumps, not a  site you can go to. @snapwiki/everybody

**Comment by RubenVerg** [comment]
GitHub can't be used as a datadump. ToS! Also I guess Miraheze could die completely (loss of funds)

**Comment by GrahamSH-LLK** [comment]
True. I couldn't find where it said no datadumps. Can you quote it? If miraheze could go down, we should export all of the data and keep it here for safekeeeping. (While keeping the actual copy on miraheze)

**Comment by RubenVerg** [comment]
sorry, I was thinking about Netlify's TOS.

**Comment by GrahamSH-LLK** [comment]
Cool! We should have @R4356th create a data dump!

**Comment by R4356th** [comment]
To be continued on the Snap<i>!</i> Forums.
