### ISSUE TITLE
Opt-out of FLoC

### ISSUE THREAD

**Issue by R4356th** [snapwiki/snapwiki.github.io#24]
FLoC is bad for privacy and I just noticed that GitHub Pages does not add HTTP header for disabling it by default.

**Comment by R4356th** [comment]
Note that the wiki has already opted out of FLoC thanks to Miraheze.

**Comment by GrahamSH-LLK** [comment]
Hmm, maybe we could get GH to disable it?

**Comment by R4356th** [comment]
My PR didn't work.

**Comment by R4356th** [comment]
I have got an evil idea. Let's either prevent users using Chrome (and other Chromium browsers once they all support FLoC) from reaching this website or show a warning to them

**Comment by R4356th** [comment]
GitHub has [opted out](https://github.blog/changelog/2021-04-27-github-pages-permissions-policy-interest-cohort-header-added-to-all-pages-sites/) of FLoC! Result of ``curl -I https://snapwiki.github.io``:
```Bash
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 5532
Server: GitHub.com
Content-Type: text/html; charset=utf-8
permissions-policy: interest-cohort=()
```
