### ISSUE TITLE
Rewrite in nuxt or hugo

### ISSUE THREAD

**Issue by GrahamSH-LLK** [snapwiki/snapwiki.github.io#30]
Jekyll is really slow, plus the current site uses Bootstrap (what was I thinking??????)

**Comment by GrahamSH-LLK** [comment]
Update: nuxt in-progress

**Comment by R4356th** [comment]
Does Nuxt have support for HTML CSS, JS etc minification?

**Comment by GrahamSH-LLK** [comment]
> Does Nuxt have support for HTML CSS, JS etc minification?

AFAIK it does it by default
